global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'servlet-jdbc-jvm'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9001' ]
        labels:
          application: 'servlet-jdbc-jvm'
  - job_name: 'servlet-jdbc-native'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9101' ]
        labels:
          application: 'servlet-jdbc-native'
  - job_name: 'reactive-r2dbc-jvm'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9002' ]
        labels:
          application: 'reactive-r2dbc-jvm'
  - job_name: 'reactive-r2dbc-native'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9102' ]
        labels:
          application: 'reactive-r2dbc-native'
