apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reactive-r2dbc-native
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "9102"
spec:
  template:
    spec:
      containers:
        - name: reactive-r2dbc-native
          image: ghcr.io/thomasvitale/reactive-r2dbc-native:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9102
          env:
            - name: BPL_JAVA_NMT_ENABLED
              value: "false"
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: reactive-r2dbc-native
