apiVersion: v1
kind: ConfigMap
metadata:
  name: reactive-r2dbc-jvm
data:
  application.yml: |
    server:
      shutdown: graceful
    spring:
      config:
        import: configtree:/workspace/secrets/*/
      lifecycle:
        timeout-per-shutdown-phase: 15s
      zipkin:
        base-url: http://tempo.observability-stack.svc.cluster.local:9411
        enabled: true
