apiVersion: v1
kind: ConfigMap
metadata:
  name: reactive-r2dbc-jvm
data:
  application.yml: |
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 15s
