apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: observability-stack
  labels:
    grafana_datasource: "true"
data:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
      - name: Tempo
      - name: Loki
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus-thomas-vitale
        access: proxy
        orgId: 1
        url: http://loki-stack-prometheus-server
        version: 1
        editable: true
