server:
  port: 9002
  netty:
    connection-timeout: 2s

spring:
  application:
    name: reactive-r2dbc-jvm
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/catalog
    pool:
      max-size: 10
  sql:
    init:
      mode: always
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: env, health, heapdump, prometheus
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
