name: Servlet JDBC JVM
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Compile and test application
        run: |
          cd servlet-jdbc-jvm
          chmod +x gradlew
          ./gradlew build
  package:
    name: Package
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Get project version
        uses: thecodemonkey/action-get-gradle-version@master
        with:
          file: servlet-jdbc-jvm/build.gradle
        id: version
      - name: Save app version as environment variable
        run: |
          echo "APP_VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
      - name: Containerize and publish image
        run: |
          cd servlet-jdbc-jvm
          chmod +x gradlew
          ./gradlew bootBuildImage \
            --imageName ghcr.io/thomasvitale/servlet-jdbc-jvm:${{ env.APP_VERSION }} \
            --publishImage \
            -PregistryUrl=ghcr.io \
            -PregistryUsername=thomasvitale \
            -PregistryToken=${{ secrets.GITHUB_TOKEN }}
